name: Test and coverage

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: |  # simulate modification of source code
          code='package calc\n\nfunc Add(x, y int) int {\nprintln("code again added")\nreturn x + y\n}'
          printf "$code" > calc1.go
          mv calc1.go calc.go
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic
      - name: test
        uses: docker://ghcr.io/buildpacks/actions/registry/request-add-entry:4.0.1
      - name: Upload coverage to Codecov
        run: |
          bash <(curl -s https://codecov.io/bash)    
